version: '3'
services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    networks:
      - bot-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - bot-network

  discord-bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
